//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegionListFinder.RegionServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StateClass", Namespace="http://schemas.datacontract.org/2004/07/RegionFinder")]
    [System.SerializableAttribute()]
    public partial class StateClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeDescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateDescription {
            get {
                return this.StateDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.StateDescriptionField, value) != true)) {
                    this.StateDescriptionField = value;
                    this.RaisePropertyChanged("StateDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCodeDescription {
            get {
                return this.ZipCodeDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeDescriptionField, value) != true)) {
                    this.ZipCodeDescriptionField = value;
                    this.RaisePropertyChanged("ZipCodeDescription");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RegionServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRegionStates", ReplyAction="http://tempuri.org/IService1/GetRegionStatesResponse")]
        RegionListFinder.RegionServiceReference.StateClass[] GetRegionStates(string stateDesc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRegionStates", ReplyAction="http://tempuri.org/IService1/GetRegionStatesResponse")]
        System.Threading.Tasks.Task<RegionListFinder.RegionServiceReference.StateClass[]> GetRegionStatesAsync(string stateDesc);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : RegionListFinder.RegionServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<RegionListFinder.RegionServiceReference.IService1>, RegionListFinder.RegionServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RegionListFinder.RegionServiceReference.StateClass[] GetRegionStates(string stateDesc) {
            return base.Channel.GetRegionStates(stateDesc);
        }
        
        public System.Threading.Tasks.Task<RegionListFinder.RegionServiceReference.StateClass[]> GetRegionStatesAsync(string stateDesc) {
            return base.Channel.GetRegionStatesAsync(stateDesc);
        }
    }
}
